[package]
name = "pleezer"
version = "0.1.0"
authors = ["Roderick van Domburg"]
edition = "2021"
rust-version = "1.78"
description = "Cross-platform Deezer Connect client"
readme = "README.md"
repository = "https://github.com/roderickvd/pleezer/"
license-file = "LICENSE.md"
keywords = ["audio", "deezer", "player"]
categories = ["multimedia::audio"]
exclude = ["arl.toml*", "config.toml*"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4.0", features = ["cargo", "derive", "env", "wrap_help"] }
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }
flate2 = "1.0"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
governor = { version = "0.6", default-features = false, features = ["std"] }
http = "1.1"
log = "0.4"
lru_time_cache = "0.11"
machine-uid = "0.5"
protobuf = "3.2"
rand = "0.8"
reqwest = { version = "0.12", features = ["brotli", "cookies", "gzip", "json", "stream"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "3.8", features = ["base64", "json"] }
sysinfo = { version = "0.30", default-features = false }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-tungstenite = { version = "0.23", features = ["native-tls"] }
toml = "0.8"
url = "2.3"
uuid = { version = "1.2", features = ["serde", "v4", "v5"] }

[build-dependencies]
protobuf-codegen = "3"