[package]
name = "pleezer"
version = "0.1.0"
authors = ["Roderick van Domburg"]
edition = "2021"
rust-version = "1.64"
description = "Cross-platform Deezer Connect client"
readme = "README.md"
repository = "https://github.com/roderickvd/pleezer/"
license = "MIT"
keywords = ["audio", "deezer", "player"]
categories = ["multimedia::audio"]
exclude = ["arl.toml*"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
async-trait = "0.1"
base64 = "0.13"
clap = { version = "4.0", features = ["cargo", "derive", "env", "wrap_help"] }
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty", "humantime"] }
flate2 = "1.0"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
governor = { version = "0.5", default-features = false, features = ["std"] }
http = "0.2"
log = "0.4"
lru_time_cache = "0.11"
machine-uid = "0.2"
protobuf = "3.2"
rand = "0.8"
reqwest = { version = "0.11", features = ["cookies", "deflate", "gzip", "json"] }
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = { version = "2.0", features = ["base64", "json"] }
sysinfo = { version = "0.26", default-features = false }
thiserror = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-tungstenite = { version = "0.17", features = ["native-tls"] }
toml = "0.5"
url = "2.3"
uuid = { version = "1.2", features = ["serde", "v4", "v5"] }

[build-dependencies]
protobuf-codegen = "3"