name: Check on Rust beta

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight

jobs:
  check-beta:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            features: --features jack

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y libasound2-dev libjack-dev

      - name: Install Rust beta
        run: rustup toolchain install beta --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check on ${{ matrix.os }} with Rust beta
        run: |
          cargo check --verbose ${{ matrix.features || '' }}
