name: Check on Rust beta

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight

jobs:
  maintenance:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and ALSA dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install Rust beta
        run: rustup toolchain install beta --profile minimal

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cross-compile for ${{ matrix.target }} on Rust beta
        run: |
          cargo build --verbose
