name: Check on Rust beta and dependency health

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            linker: gcc-aarch64-linux-gnu
            cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            linker: gcc-arm-linux-gnueabihf
            cross: true
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools and ALSA dependencies (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential libasound2-dev pkg-config

      - name: Install cross compiler (aarch64 and armv7 only)
        if: matrix.cross
        run: |
          sudo apt-get install -y ${{ matrix.linker }}

      - name: Install Rust beta
        run: rustup toolchain install beta

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Cross-compile for ${{ matrix.target }} on Rust beta
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --verbose --target ${{ matrix.target }}
