name: Check on Rust beta and dependency health

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust stable for security audit
      run: rustup install stable

    - name: Run security audit
      run: cargo install cargo-audit && cargo audit

  unused-dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly and udeps for unused dependency check
      run: |
        rustup install nightly
        rustup component add rustc-dev llvm-tools-preview --toolchain nightly
        cargo +nightly install cargo-udeps

    - name: Check for unused dependencies
      run: cargo +nightly udeps --all-targets

  beta-cross-compilation:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, x86_64-apple-darwin, x86_64-pc-windows-msvc]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust beta on ${{ matrix.os }}
      run: rustup install beta

    - name: Add cross-compilation target ${{ matrix.target }} on ${{ matrix.os }}
      run: rustup target add ${{ matrix.target }}

    - name: Build ${{ matrix.target }} on ${{ matrix.os }} (beta)
      run: cargo build --verbose --target ${{ matrix.target }}

    - name: Upload binaries for ${{ matrix.target }} on ${{ matrix.os }} (beta)
      uses: actions/upload-artifact@v3
      with:
        name: my-binary-${{ matrix.target }}-beta
        path: target/${{ matrix.target }}/debug/
